local M = {}
local d = require("fused.palletes.dark")

M.dark_pallete = {
    black2 = d.surface2,
    black = d.surface,
    dark = d.dark,
    white = d.white,
    text = d.text,
    string = d.ceil,
    cp0 = d.compliment0,
    cp1 = d.compliment1,
    cp2 = d.compliment2,
    cp3 = d.compliment3,
    cp4 = d.compliment4,
    cp5 = d.compliment5,
    cp6 = d.compliment6,
    pink = d.china_pink,
    light_pink = d.baker_miller_pink,
    wred = d.candy_pink,
    deep_pink = d.cyclamen,
    red = d.pink_red,
    error_red = d.cinnabar,
    magenta = d.lavender_magenta,
    dmagenta = d.magenta_dark,
    wmagenta = d.blue,
    green = d.very_light_malachite_green,
    teal = d.teal,
    lgreen = d.one_dark_green,
    dgreen = d.limerick_green,
    lyellow = d.flax,
    yellow = d.yellow,
    dyellow = d.orange,
    radish_pink = d.big_foot_feet,
    blue = d.aero,
    sky = d.sky,
    wblue = d.cyan,
    sky_blue = d.french_sky_blue,
}

return M
